# Pandas

Pandas is a fast, flexible, and powerful open-source data manipulation and analysis library built on top of the Python programming language

Pandas gives labels and table semantics.

The two core pandas objects:
1. Series -> 1d labeled data.
2. DataFrame -> 2d labeled table.

In [1]:
import pandas as pd

### Lesson 1: DataFrame.

A dataframe gives :
1. Rows -> observations / samples
2. Columns -> features / variables
3. Index -> row labels
4. Values -> actual data

In [2]:
# creating a simple dataFrame.
df = pd.DataFrame({
    "student_id": [101, 102, 103],
    "maths": [34, 45, 56]
})
df

   student_id  maths
0         101     34
1         102     45
2         103     56

### Lesson 2: Series

In [3]:
scores = pd.Series(
    [85, 86, 87],
    index=["A", "B", "C"],
    name="Math Scores"
)
scores

A    85
B    86
C    87
Name: Math Scores, dtype: int64

In [4]:
type(scores)

pandas.Series

Series has both values and an index.

In [5]:
scores.index

Index(['A', 'B', 'C'], dtype='str')

In [7]:
scores.values

array([85, 86, 87])

In [8]:
scores.name

'Math Scores'

Label-Based Access

In [10]:
scores["B"]  # Pandas labels matter most.

np.int64(86)

In [13]:
# Create a simple dataFrame.
df = pd.DataFrame({
    "name": ["Arun", "Bala", "Charan", "Divya"],
    "age": [20, 21, 19, 22],
    "cgpa": [8.2, 7.8, 9.1, 8.7],
    "placed": [False, True, False, True]
})

df

     name  age  cgpa  placed
0    Arun   20   8.2   False
1    Bala   21   7.8    True
2  Charan   19   9.1   False
3   Divya   22   8.7    True

In [14]:
# custom index
df = pd.DataFrame({
    "age": [20, 21, 19],
    "cgpa": [8.2, 8.3, 8.4]
},
index=["STU101", "STU102", "STU103"]
)
df

        age  cgpa
STU101   20   8.2
STU102   21   8.3
STU103   19   8.4

### Lesson 3: DataFrame inspection.

In [15]:
# dataframe inspection.
df = pd.DataFrame({
    "name": ["Arun", "Bala", "Charan", "Divya", "Esha"],
    "age": [20, 21, 19, 22, 20],
    "cgpa": [8.2, 7.8, 9.1, 8.7, 8.5],
    "placed": [False, True, False, True, True]
})

In [17]:
# preview first rows
df.head(3) # default value is 5

     name  age  cgpa  placed
0    Arun   20   8.2   False
1    Bala   21   7.8    True
2  Charan   19   9.1   False

In [19]:
# preview last rows
df.tail(3)

     name  age  cgpa  placed
2  Charan   19   9.1   False
3   Divya   22   8.7    True
4    Esha   20   8.5    True

In [20]:
df.info() # gives the range datatypes of the cols in the df.

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   cgpa    5 non-null      float64
 3   placed  5 non-null      bool
dtypes: bool(1), float64(1), int64(1), str(1)
memory usage: 257.0 bytes

In [21]:
# statistics of the dataframe
df.describe()

             age     cgpa
count   5.000000  5.00000
mean   20.400000  8.46000
std     1.140175  0.49295
min    19.000000  7.80000
25%    20.000000  8.20000
50%    20.000000  8.50000
75%    21.000000  8.70000
max    22.000000  9.10000

### Lesson 4: Column Selection.

In [22]:
df['cgpa']

0    8.2
1    7.8
2    9.1
3    8.7
4    8.5
Name: cgpa, dtype: float64

In [23]:
type(df['cgpa']) # 1d means series. Therefore, got series

pandas.Series

In [24]:
df[["name", "cgpa"]]

     name  cgpa
0    Arun   8.2
1    Bala   7.8
2  Charan   9.1
3   Divya   8.7
4    Esha   8.5

In [25]:
 type(df[["name", "cgpa"]])

pandas.DataFrame

In [27]:
X = df[["cgpa"]]
X.shape

(5, 1)

In [28]:
X = df["cgpa"]
X.shape

(5,)

### Lesson 5: loc vs iloc

loc: labels

iloc: integer positions

In [29]:
df = pd.DataFrame(
    {
        "age": [20, 21, 19],
        "cgpa": [8.2, 7.8, 9.1]
    },
    index=["STU101", "STU102", "STU103"]
)
df

        age  cgpa
STU101   20   8.2
STU102   21   7.8
STU103   19   9.1

In [32]:
# loc: label based selection
df.loc["STU101"]

age     20.0
cgpa     8.2
Name: STU101, dtype: float64

In [35]:
# multiple rows and cols
df.loc["STU102", "age"]

np.int64(21)

Syntax:

df.loc[row_labels, column_labels] -> value at the column_label

In [38]:
df.loc[["STU101", "STU102"], ["age", "cgpa"]]

        age  cgpa
STU101   20   8.2
STU102   21   7.8

iloc: Position based selection.

In [39]:
df.iloc[0]

age     20.0
cgpa     8.2
Name: STU101, dtype: float64

In [44]:
df.iloc[1, 1]

np.float64(7.8)

syntax: df.iloc[row_positions, column_positions]

In [47]:
# slicing
df.iloc[0:2] # 0 - include, 2 - exclude.

        age  cgpa
STU101   20   8.2
STU102   21   7.8

In [48]:
df.loc["STU101": "STU103"] # includes both.

        age  cgpa
STU101   20   8.2
STU102   21   7.8
STU103   19   9.1

In [51]:
# masking.
df[df["cgpa"] > 8.0] # just like in numpy &, | are used to concat more than 1 statement.

        age  cgpa
STU101   20   8.2
STU103   19   9.1

### Lesson 6: Query

In [53]:
# instead of using & or | for the statements use query() for better readablity.
df.query("cgpa > 8.0 and age < 30")

        age  cgpa
STU101   20   8.2
STU103   19   9.1

In [56]:
min_cgpa = 7.3
df.query("cgpa > @min_cgpa") # @ is used to access the values outside the dataframe.

        age  cgpa
STU101   20   8.2
STU102   21   7.8
STU103   19   9.1

### Lesson 7: Membership Filtering with isin()

In [57]:
df = pd.DataFrame({
    "name": ["Arun", "Bala", "Charan", "Divya"],
    "department": ["CSE", "ECE", "CSE", "MECH"],
    "cgpa": [8.2, 7.8, 9.1, 8.0]
})

In [58]:
df[
    df["department"].isin(["CSE", "ECE"])
]

     name department  cgpa
0    Arun        CSE   8.2
1    Bala        ECE   7.8
2  Charan        CSE   9.1

In [59]:
df[df["cgpa"].between(1, 2)] # fetchs values between them.

Empty DataFrame
Columns: [name, department, cgpa]
Index: []

In [60]:
df.sort_values("cgpa", ascending=False)

     name department  cgpa
2  Charan        CSE   9.1
0    Arun        CSE   8.2
3   Divya       MECH   8.0
1    Bala        ECE   7.8

In [62]:
df.sort_values(
    by=["cgpa", "department"],
    ascending=[True, False]
)

     name department  cgpa
1    Bala        ECE   7.8
3   Divya       MECH   8.0
0    Arun        CSE   8.2
2  Charan        CSE   9.1

In [66]:
filtered = df[df["cgpa"] < 9.0]
filtered.index

Index([0, 1, 3], dtype='int64')

In [64]:
filtered.reset_index()

   index   name department  cgpa
0      0   Arun        CSE   8.2
1      1   Bala        ECE   7.8
2      3  Divya       MECH   8.0

In [67]:
filtered.reset_index(drop=True)

    name department  cgpa
0   Arun        CSE   8.2
1   Bala        ECE   7.8
2  Divya       MECH   8.0

In [72]:
# Setting a meaningful index.
df = pd.DataFrame({
    "student_id": ["S101", "S102", "S103"],
    "name": ["Arun", "Bala", "Charan"],
    "cgpa": [8.2, 7.8, 9.1]
})

In [73]:
df = df.set_index("student_id")

In [74]:
df

              name  cgpa
student_id
S101          Arun   8.2
S102          Bala   7.8
S103        Charan   9.1

In [75]:
# Selecting by datatype.
df = pd.DataFrame({
    "age": [20, 21, 22],
    "cgpa": [8.2, 7.8, 9.1],
    "department": ["CSE", "ECE", "CSE"],
    "placed": [True, False, True]
})

In [77]:
numeric_df = df.select_dtypes(
    include="number"
)
numeric_df

   age  cgpa
0   20   8.2
1   21   7.8
2   22   9.1

In [78]:
text_df = df.select_dtypes(
    include="object"
)
text_df

C:\Users\omsai\AppData\Local\Temp\ipykernel_29320\3455779454.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_df = df.select_dtypes(

  department
0        CSE
1        ECE
2        CSE

In [79]:
df.select_dtypes(
    exclude="number"
)

  department  placed
0        CSE    True
1        ECE   False
2        CSE    True

Series
    1D labeled data

DataFrame
    2D labeled table

df["col"]
    returns Series

df[["col"]]
    returns DataFrame

loc
    label based

iloc
    position based

query()
    readable filtering

isin()
    membership filtering

between()
    range filtering

set_index()
    assign meaningful index

reset_index()
    restore sequential index

Index Alignment
    Pandas aligns data by labels

select_dtypes()
    separate numeric/categorical features

### Lesson 8: Missing values in the dataset.

In [81]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["Arun", "Bala", "Charan", "Divya", "Esha"],
    "age": [20, None, 19, 22, None],
    "cgpa": [8.2, 7.8, np.nan, 8.7, 8.5],
    "department": ["CSE", "ECE", None, "CSE", "ECE"]
})

df

     name   age  cgpa department
0    Arun  20.0   8.2        CSE
1    Bala   NaN   7.8        ECE
2  Charan  19.0   NaN        NaN
3   Divya  22.0   8.7        CSE
4    Esha   NaN   8.5        ECE

In [83]:
# detect missing values
df.isna()
# False - if not missing
# True - if missing

    name    age   cgpa  department
0  False  False  False       False
1  False   True  False       False
2  False  False   True        True
3  False  False  False       False
4  False   True  False       False

In [85]:
df.isnull()  # isna and isnull are exactly identical methods.

    name    age   cgpa  department
0  False  False  False       False
1  False   True  False       False
2  False  False   True        True
3  False  False  False       False
4  False   True  False       False

In [87]:
# count missing values per column
df.isnull().sum() # think of it True -> 1 and False -> 0

name          0
age           2
cgpa          1
department    1
dtype: int64

In [89]:
df.isna().sum().sum() # returns -> total missing values.

np.int64(4)

In [91]:
df.isna().mean() * 100 # percentage of missing values.

name           0.0
age           40.0
cgpa          20.0
department    20.0
dtype: float64

In [93]:
missing_report = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missin_percent": df.isna().mean() * 100,
})
missing_report

            missing_count  missin_percent
name                    0             0.0
age                     2            40.0
cgpa                    1            20.0
department              1            20.0

In [95]:
missing = df.isna().sum()
missing[missing > 0]

age           2
cgpa          1
department    1
dtype: int64

In [98]:
df.dropna() # removes the missing null values

    name   age  cgpa department
0   Arun  20.0   8.2        CSE
3  Divya  22.0   8.7        CSE

In [99]:
df.dropna(how="any")

    name   age  cgpa department
0   Arun  20.0   8.2        CSE
3  Divya  22.0   8.7        CSE

In [100]:
df.dropna(how="all")

     name   age  cgpa department
0    Arun  20.0   8.2        CSE
1    Bala   NaN   7.8        ECE
2  Charan  19.0   NaN        NaN
3   Divya  22.0   8.7        CSE
4    Esha   NaN   8.5        ECE

isna()
    detect missing values

isna().sum()
    missing count

isna().mean() * 100
    missing percentage

dropna()
    remove missing rows/columns

fillna()
    fill missing values

ffill()
    forward fill

bfill()
    backward fill

interpolate()
    estimate continuous missing values

duplicated()
    detect duplicates

drop_duplicates()
    remove duplicates

astype()
    strict conversion

pd.to_numeric()
    safe numeric conversion

pd.to_datetime()
    datetime conversion

convert_dtypes()
    infer nullable Pandas types

.str
    vectorized string cleaning

replace()
    standardize values

map()
    direct value mapping

unique()
    inspect categories

value_counts()
    category frequencies

.loc[]
    safe conditional assignment

.copy()
    explicit independent DataFrame

Raw magnitude relationship?
    → ratio feature

Features influence each other?
    → interaction feature

Curved relationship?
    → polynomial feature

Heavy positive skew?
    → log transformation

Meaningful ranges?
    → cut()

Relative quantile groups?
    → qcut()

Ordered categories?
    → map()

Nominal categories?
    → one-hot encoding

High-cardinality categories?
    → frequency/count encoding

Tiny categories?
    → rare category grouping

Date column?
    → year/month/day/weekend

Circular variable?
    → sin/cos encoding

Group context matters?
    → groupby + transform

Relative group position?
    → deviation/rank

Sequential data?
    → shift/diff

Local temporal behavior?
    → rolling

Cumulative history?
    → expanding/cumsum

Text column?
    → length/count/regex features